---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Create file system for volumes
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ volume_device_comm }}"
  when: volume_device_comm is defined

- name: Create a mount point directory
  file:
    path: "{{ volume_mount_point_comm }}"
    state: directory
    mode: "777"

- name: Mount volumes
  mount:
    path: "{{ volume_mount_point_comm }}"
    src: "{{ volume_device_comm }}"
    fstype: ext4
    state: mounted
  when: volume_device_comm is defined
