---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Gather facts
  setup:
    gather_subset: all

- name: Assert local proxy already configured.
  shell: grep "^http_proxy" /etc/environment
  register: test_proxy_exist
  failed_when: "test_proxy_exist.rc == 2"
  changed_when: false

- name: Configure proxy
  template:
    src: env.j2
    dest: /etc/environment
    force: true
  when: test_proxy_exist.rc == 1

- shell: cat /etc/environment
  register: env_content

- debug:
    var: env_content.stdout_lines

- name: Restart SSH service
  import_tasks: restart_ssh.yaml

- name: Configure instance timezone to Australia/Melbourne
  timezone:
    name: Australia/Melbourne

- name: Restart Cron service
  service:
    name: cron
    state: restarted

- name: Activate NTP service
  shell: timedatectl set-ntp on

- name: Install general packages
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "python-setuptools",
        "software-properties-common",
        "vim",
      ]
    state: latest
    update_cache: yes
    install_recommends: no

- name: Restart SSH service.
  import_tasks: restart_ssh.yaml
