---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Start Watchtower
  docker_container:
    name: ccc_watchtower_{{ ansible_hostname }}
    image: containrrr/watchtower
    state: started
    restart: no
    env:
      http_proxy: http://wwwproxy.unimelb.edu.au:8000
      https_proxy: http://wwwproxy.unimelb.edu.au:8000
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000
      ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: https://hooks.slack.com/services/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
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower_{{ ansible_hostname }}
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#deployment"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":male_mage:"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  become: yes
