---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Create volumes
  os_volume:
    display_name: "{{ item.vol_name }}"
    size: "{{ item.vol_size }}"
    availability_zone: "{{ avail_zone_comm }}"
    wait: yes
    timeout: 600
    state: present
  loop: "{{ volumes }}"
  register: os_vol

- name: Create a list of volume ids
  set_fact:
    openstack_vols: "{{ openstack_vols | default([]) + [item.id] }}"
  loop: "{{ os_vol.results }}"
  no_log: true

- debug:
    msg: "Volumes with id {{ openstack_vols }} have been created"
