---
- name: Start Client
  docker_container:
    name: ccc_client_{{ ansible_hostname }}
    image: kvoli/ccc-client:latest
    state: started
    restart: yes
    ports:
    - "8000:5000"
    env:
      COUCHDB_USER: "{{ vault_couchdb_user }}"
      COUCHDB_PASSWORD: "{{ vault_couchdb_password }}"
      NODE_ID: "{{ ansible_hostname }}"
      VIRTUAL_HOST: "a.unimelb-comp90024-2020-grp-11.cloud.edu.au"
      VIRTUAL_PORT: "8000"
  become: yes
