---
- name: Transfer harvester application
  copy:
    src: /home/mmarasco/Repositories/CCC-Assignment-2/harvester
    dest: /home/ubuntu
    directory_mode: yes
    force: yes
    owner: ubuntu
    mode: "755"

- name: Remove existing harvester
  docker_container:
    name: "{{ ansible_hostname }}_harvester"
    state: absent

# SET DOCKER PROXY
- name: Build harvester
  shell: docker build -t  stream .
  args:
    chdir: /home/ubuntu/harvester
  become: yes

- name: Start harvester
  docker_container:
    name: "{{ ansible_hostname }}_harvester"
    image: stream
    network_mode: host
    state: started
    restart: yes
    env:
      COUCHDB_USER: "{{ vault_couchdb_user }}"
      COUCHDB_PASSWORD: "{{ vault_couchdb_password }}"
      NODE_ID: "{{ ansible_hostname }}"
      TWITTER_CONSUMER_KEY: "{{ TWITTER[ansible_hostname].TWITTER_CONSUMER_KEY }}"
      TWITTER_CONSUMER_SECRET: "{{ TWITTER[ansible_hostname].TWITTER_CONSUMER_SECRET }}"
      TWITTER_ACCESS_TOKEN: "{{ TWITTER[ansible_hostname].TWITTER_ACCESS_TOKEN }}"
      TWITTER_ACCESS_TOKEN_SECRET: "{{ TWITTER[ansible_hostname].TWITTER_ACCESS_TOKEN_SECRET }}"
  become: yes
