---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Remove existing harvester
  docker_container:
    name: "{{ ansible_hostname }}_harvester"
    state: absent

- name: Start harvester
  docker_container:
    name: "{{ ansible_hostname }}_harvester"
    image: kvoli/ccc-stream
    network_mode: host
    state: started
    restart: yes
    env:
      COUCHDB_USER: "{{ vault_couchdb_user }}"
      COUCHDB_PASSWORD: "{{ vault_couchdb_password }}"
      NODE_ID: "{{ ansible_hostname }}"
      TWITTER_CONSUMER_KEY: "{{ TWITTER[ansible_hostname].TWITTER_CONSUMER_KEY }}"
      TWITTER_CONSUMER_SECRET: "{{ TWITTER[ansible_hostname].TWITTER_CONSUMER_SECRET }}"
      TWITTER_ACCESS_TOKEN: "{{ TWITTER[ansible_hostname].TWITTER_ACCESS_TOKEN }}"
      TWITTER_ACCESS_TOKEN_SECRET: "{{ TWITTER[ansible_hostname].TWITTER_ACCESS_TOKEN_SECRET }}"
      http_proxy: http://wwwproxy.unimelb.edu.au:8000
      https_proxy: http://wwwproxy.unimelb.edu.au:8000
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000
      ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
  become: yes
