---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Install Node.js
  apt:
    name: ["build-essential", "nodejs"]
    state: latest
    update_cache: yes

- name: Install npm packages
  shell: >
    npm install
  args:
    executable: /bin/bash
    chdir: /home/mmarasco/Repositories/CCC-Assignment-2/client

- name: Build application website
  shell: >
    node --max_old_space_size=15000 /usr/bin/npm run build
  args:
    executable: /bin/bash
    chdir: /home/mmarasco/Repositories/CCC-Assignment-2/client
