---
- name: Initialise CouchDB cluster (1/3)
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ vault_couchdb_user }}:{{ vault_couchdb_password }}@localhost:5984/_cluster_setup
    -d "{"action": "enable_cluster", "bind_address": "0.0.0.0",
    "username": "{{ vault_couchdb_user }}", "password":"{{ vault_couchdb_password }}",
    "port": 5984, "node_count": "{{ groups['all'] | length }}",
    "remote_node": "{{ hostvars[item]['ansible_host'] }}",
    "remote_current_user": "{{ vault_couchdb_user }}", "remote_current_password": "{{ vault_couchdb_password }}" }"
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname

- name: Initialise CouchDB cluster (2/3)
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ vault_couchdb_user }}:{{ vault_couchdb_password }}@localhost:5984/_cluster_setup
    -d '{"action": "add_node", "host": "{{ hostvars[item]['ansible_host'] }}",
    "port": 5984, "username": "{{ vault_couchdb_user }}", "password":"{{ vault_couchdb_password }}"}'
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname

- name: Initialise CouchDB cluster (3/3)
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/_cluster_setup
    -d '{"action": "finish_cluster"}'

- name: Create Twitter database
  shell: >
    curl -X PUT http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/tweets

- name: Create User database
  shell: >
    curl -X PUT http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/users

- name: Create Location database
  shell: >
  curl -X PUT http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/located_tweets
  
- name: Create Website database
  shell: >
    curl -X PUT http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/website_suburb

- name: Upload design documents (1/2)
  uri:
    url: http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/located_tweets/suburb_stats
    method: POST
    src: suburb.json

- name: Upload design documents (2/2)
  uri:
    url: http://{{ vault_couchdb_user }}:{{ vault_couchdb_user }}@localhost:5984/tweets/user_stats
    method: POST
    src: user.json