---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Initialise keypair
  os_keypair:
    name: "{{ keypair_name_comm }}"
    timeout: 600
    wait: yes
    state: present
