# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
dependencies:
  - { role: openstack_environment }
  - { role: openstack_keypair }
  - { role: openstack_security_groups }
