---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840

# Configure instances with common requirements.
- hosts: all
  vars_files:
    - host_vars/general_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_general
    - openstack_mount
