---
# Configure instances with common requirements.
- hosts: all
  vars_files:
    - host_vars/general_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_general
    - openstack_mount

# Set up CouchDB Docker container on all instances.
- hosts: all
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_all

# Create CouchDB cluster.
- hosts: instance_1
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_master

# Configure nginx.
- hosts: instance_2
  vars_files:
    - host_vars/general_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_nginx

# Start harvesters.
- hosts: instance_3, instance_4
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_watchtower
    - docker_harvest
    - slack_notification

# Start website pre-processor.
- hosts: instance_3
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_watchtower
    - docker_websitedata
    - slack_notification

# Start website.
- hosts: instance_1
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - config_watchtower
    - config_letsencrypt
    - docker_client
    - slack_notification
