---
# Configure instances with common requirements.
- hosts: instance_3, instance_4
  vars_files:
    - host_vars/general_vars.yaml
    - host_vars/vault.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_watchtower
    - docker_harvest
    - slack_notification
