---
# COMP90024
# Team 11
# Marco Marasco - 834882
# Austen McClernon - 834063
# Sam Mei - 1105817
# Cameron Wong - 1117840
- name: Create security groups
  os_security_group:
    name: "{{ security_groups.name }}"
    description: "{{ security_groups.description }}"
    state: present

- set_fact:
    os_all_security_groups: "{{ [ security_groups.name ] }}"

- name: Set security rules group (1/2)
  os_security_group_rule:
    security_group: "{{ security_groups.name }}"
    protocol: "{{ security_groups.protocol }}"
    remote_group: "{{ security_groups.remote_group }}"
    state: present

- name: Set security rules group (2/2)
  os_security_group_rule:
    security_group: "{{ security_groups.name }}"
    protocol: "{{ security_groups.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ security_groups.remote_ip_prefix }}"
    state: present
  loop: "{{ security_groups.rules }}"
